#+title: Learning Haskell

** Books

***** DONE - Learn you a Haskell for Great Good - Read this book along with solving exercises from first few chapters from haskell mooc(till chapter4a).

***** Haskell Programming from First Principles(HPFFP) - This book is too verbose and just eats my energy before heading to exercises. I have read up to 6th Chapter in this book.

***** Get Programming with Haskell - I have read this book for chap17(Monoids and Semigroups), Chap21 and later.

** Exercises

***** Started with Learn you a Haskell book, simultaneously solve *learn4haskell exercises* from github.
***** haskell-mooc - solved a few chapters from this repo.
***** cis194(spring 2013) - Solved the first exercise only, the rest seems to be out of my understanding.

** Projects

***** [[https://github.com/fpindia/fpindia-site][FPIndia Static Site]] - Contributed to the static site which was utilising the unreleased development on multisite branch - [[https://github.com/EmaApps/ema/pull/81][multisite rewrite]].
***** IDEA [[https://github.com/udaycruise2903/ideas/issues/1][CLI app for displaying the haskell meetups around the world]]

** Conferences

***** Haskell exchange - I attended the beginner track of it in 2021. It was gave me different perspectives on beginner struggles and how to overcome them.
***** Haskell love - I have to rewatch the videos of these.
***** [[https://www.functionalconf.com/][Functional Conference 2022(March 2022)]] - I did not watch this conference after a few sessions.

** Mailing Lists

***** [[https://haskellweekly.news/][haskellweekly]] - I have been reading this every week, but not trying out things in blogs from last  6 months.

** Good Articles/Blogs

***** [[https://adit.io/posts/2013-04-17-functors,_applicatives,_and_monads_in_pictures.html][Functor, Applicatives and Monads in pictures]]
***** [[https://planet.haskell.org/][Planet Haskell]] - Compilation of latest blog posts on haskell.
***** [[https://www.schoolofhaskell.com/school/starting-with-haskell/basics-of-haskell][School of haskell]]
***** TODO [[https://serokell.io/blog/lexing-with-alex][Parsing with haskell]]
***** [[https://serokell.io/blog/whats-that-typeclass-monoid][Monoids]]

** Meetups

***** Las Gatos FP group - attended their *Haskell in Depth* Book discussion session.
***** Portland FP group - Haven't attended a single session till now.
***** Berlin FP group - This group conducts a online session every month called *Bring Your Project, Get help with your code & socialise*.
***** [[https://twitter.com/FunctionalIndia/status/1553237013196726272][FP India Meetup]] - I conducted this meetup this year. It was really wonderful to meet a few haskellers.

** Podcasts

***** Haskell Weekly by Taylor Fausak - Listened to a few podcasts. I need to listen to this frequently.
